name: Build and Package BMC SDK

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        token: ${{ env.GH_TOKEN }}
        submodules: recursive

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Get CMake
      uses: lukka/get-cmake@latest

    - name: Set up environment
      run: |
        echo "SUBPROJECT_DIR=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Build the Bridge, library and examples (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        dir
        .\build.bat win32

    - name: Stage artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        .\stage.bat

    - name: Upload build artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifacts
        path: staging/
