name: Build and Package BMC SDK

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [32, 64]
        include:
          - arch: 32
            arch_python: x86
            arch_cmake: win32
          - arch: 64
            arch_python: x64
            arch_cmake: x64
        exclude:
          - os: ubuntu-latest
            arch: 32
          - os: macos-latest
            arch: 32

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:

    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        token: ${{ env.GH_TOKEN }}
        submodules: recursive

    - name: Get CMake
      uses: lukka/get-cmake@latest

    - name: Get version from VERSION file
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      shell: bash

    - name: Build and stage the library and examples (Mac and Linux)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        ./build_and_stage.sh

    - name: Build the library and examples (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        dir
        .\build_and_stage.bat ${{ matrix.arch_cmake }}

    - name: Create Windows installer
      if: matrix.os == 'windows-latest'
      uses: joncloud/makensis-action@v4
      with:
        script-file: bmc_sdk_installer.nsi
        arguments: /DOUTFILE=BinhoMissionControlSDK-${{ env.VERSION }}-${{ matrix.arch }}.exe

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-artifacts
        path: staging/

    - name: Upload Windows installer
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: BinhoMissionControlSDK-${{ env.VERSION }}-${{ matrix.arch }}.exe
        path: BinhoMissionControlSDK-${{ env.VERSION }}-${{ matrix.arch }}.exe
